### ISSUE TITLE
thread safety of workload generator

### ISSUE THREAD

**Issue by ug93tad** [basicthinker/YCSB-C#2]
Is CoreWorkload thread safe? I understand from reading the source that CoreWorkload object is shared between multiple DelegateClient threads. The threads will invoke NextSequenceKey(.) and NextTransactionKey(.) concurrently, which will probably lead to race conditions?

**Comment by basicthinker** [comment]
The workload generator is not thread safe, but each client holds its own generator. You can safely use the benchmark with multiple client threads (by specifying "-threads" in the ycsbc command line). Thanks.

**Comment by ug93tad** [comment]
it looks from the code that each client is initialize with the same generator (CoreWorkload). Am I missing something here?

ycsb.cc:29   ycsb::Client client(*db, *wl)

**Comment by basicthinker** [comment]
Thanks for pointing out this bug. I've made all generator operations thread-safe (but their initializations are not). Please see [bef3a73](https://github.com/basicthinker/YCSB-C/commit/bef3a731f506b39d33ddc20e2228d5f2356807e4) and previous seven commits. Please let me know if any problems.
